from .omc import router as omc_router
from .concept import router as concept_router
from .method import router as method_router
from .tool import router as tool_router
from .kpi import router as kpi_router
from .question import router as question_router
from .evidence import router as evidence_router
from .risk import router as risk_router
from .recommendation import router as recommendation_router
from .relationship import router as relationship_router
